# Generated by Django 3.2.13 on 2022-07-04 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_firstname', models.CharField(max_length=128)),
                ('employee_lastname', models.CharField(max_length=128)),
                ('employee_id', models.IntegerField()),
                ('extra_large', models.BooleanField(default=False)),
                ('specification', models.CharField(max_length=128)),
                ('selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menus.menuoption')),
            ],
        ),
    ]
